### ISSUE TITLE
Any possible way to port this to Windows 10?

### ISSUE THREAD

**Issue by lastmetroid** [marcharding/DellFanControl#2]
Please... ? As a pre compiled package. Maybe even make a little cool tool out of it, with implemented temp reading, so it just turns off the fans if temps are for example under 60°c. Also, make the whole sign stuff somehow better and put it all into one solution. What are the risks to turning off signed drivers? Can it always be turned on again? I found a precompiled zip file on the web of this tool but I dont trust it. Why is the exe 16MB in size?

**Comment by uncttao** [comment]
It works on Windows 10 pretty well.
* I built it myself using Visual Studio 2017.

**Comment by lastmetroid** [comment]
It would be nice to have a precompiled version though here... I dont want to compile it myself.

**Comment by marcharding** [comment]
I added an alpha pre release. **Use at out own risk**.
