### ISSUE TITLE
Fan keeps spinning when closing lid.

### ISSUE THREAD

**Issue by uncttao** [marcharding/DellFanControl#3]
As stated in the title. If this is fixed, it would be perfect!

**Comment by marcharding** [comment]
Hm, it works for me. I'll take a look again.

**Comment by uncttao** [comment]
More investigation: the fan keeps spinning if closing the lid means "sleep", but there is no spinning when it's set to "hibernate".
Plus, when awoken from hibernation, I have to manually turn on "Enable Custom Fan Control" for it to work again.

**Comment by uncttao** [comment]
Hi, allow me to respectfully ask if there is any follow-up on this issue?

**Comment by marcharding** [comment]
Hey, sorry for the late response.

It works for me, no matter if closing the lid means sleep or hibernate.

Also i do not have to turn it on again after the laptop wakes from hibernation. 

I have no clue why it is not working for you, sorry.

**Comment by marcharding** [comment]
Can't reproduce.
